import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { AuthProvider } from "@/context/auth";
import AuthButtons from "@/components/auth-buttons";
import { HomeIcon } from "lucide-react";
import { Toaster } from "@/components/ui/sonner";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased`}
      >
        <AuthProvider>
          {/* TODO - Make the navbar sticky */}
          {/* NOTE - Be aware of behavior of Property View Page as the sticky property snapshot will go over */}
          <nav className="bg-accent p-5 h-24 flex items-center justify-between">
            <Link href="/" className="text-3xl tracking-widest flex gap-2 items-center uppercase">
              <HomeIcon />
              <span>Fire Homes</span>
            </Link>
            <ul className="flex items-center justify-between gap-6">
              <li>
                <Link href="/property-search" className="uppercase tracking-widest hover:underline">Property Search</Link>
              </li>
              <li>
                <AuthButtons />
              </li>
            </ul>
          </nav>
          {children}
          <Toaster richColors closeButton />
        </AuthProvider>
      </body>
    </html>
  );
}
